// Message state
export const HISTORY_MESSAGE_GET = 'HISTORY_MESSAGE_GET';

// Sockets connection
export const SOCKET_CONNECTION_REQUEST = 'SOCKET_CONNECTION_REQUEST';
export const SOCKET_CONNECTION_SUCCESS = 'SOCKET_CONNECTION_SUCCESS';
export const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR';
